// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nameClient.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Sufs {
  public static partial class FileManagement
  {
    static readonly string __ServiceName = "sufs.FileManagement";

    static readonly grpc::Marshaller<global::Sufs.CreateRequest> __Marshaller_CreateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Sufs.CreateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Sufs.CreateReply> __Marshaller_CreateReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Sufs.CreateReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Sufs.CreateRequest, global::Sufs.CreateReply> __Method_CreateFile = new grpc::Method<global::Sufs.CreateRequest, global::Sufs.CreateReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateFile",
        __Marshaller_CreateRequest,
        __Marshaller_CreateReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Sufs.NameClientReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FileManagement</summary>
    public abstract partial class FileManagementBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Sufs.CreateReply> CreateFile(global::Sufs.CreateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FileManagement</summary>
    public partial class FileManagementClient : grpc::ClientBase<FileManagementClient>
    {
      /// <summary>Creates a new client for FileManagement</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public FileManagementClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FileManagement that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public FileManagementClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected FileManagementClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected FileManagementClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Sufs.CreateReply CreateFile(global::Sufs.CreateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateFile(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Sufs.CreateReply CreateFile(global::Sufs.CreateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateFile, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Sufs.CreateReply> CreateFileAsync(global::Sufs.CreateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateFileAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Sufs.CreateReply> CreateFileAsync(global::Sufs.CreateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateFile, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override FileManagementClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FileManagementClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(FileManagementBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateFile, serviceImpl.CreateFile).Build();
    }

  }
}
#endregion
