// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nameNode.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sufs {

  /// <summary>Holder for reflection information generated from nameNode.proto</summary>
  public static partial class NameNodeReflection {

    #region Descriptor
    /// <summary>File descriptor for nameNode.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NameNodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5uYW1lTm9kZS5wcm90bxIEc3VmcyJBCg1DcmVhdGVSZXF1ZXN0EhEKCW51",
            "bUJsb2NrcxgBIAEoBRILCgNkaXIYAiABKAkSEAoIZmlsZU5hbWUYAyABKAki",
            "VQoOQ3JlYXRlUmVzcG9uc2USDwoHYmxvY2tJRBgCIAEoBRIRCglyZXBGYWN0",
            "b3IYAyABKAUSDAoERE5pZBgEIAMoCUoECAEQAlILYmxvY2tJRExpc3QiMgoM",
            "QmxvY2tJRF9TaXplEg8KB2Jsb2NrSUQYASABKAUSEQoJYmxvY2tTaXplGAIg",
            "ASgCIj8KDVJlcG9ydFJlcXVlc3QSDAoERE5pZBgBIAEoCRIPCgdibG9ja0lE",
            "GAMgASgFSgQIAhADUglibG9ja0xpc3QiJgoOUmVwb3J0UmVzcG9uc2USFAoM",
            "YWNrbm93bGVkZ2VkGAEgASgIIhkKCUhCcmVxdWVzdBIMCgRETmlkGAEgASgJ",
            "IiIKCkhCcmVzcG9uc2USFAoMYWNrbm93bGVkZ2VkGAEgASgIIh8KC1BhdGhS",
            "ZXF1ZXN0EhAKCGRpcl9wYXRoGAEgASgJIiwKEExpc3RQYXRoUmVzcG9uc2US",
            "GAoQZGlyX3BhdGhDb250ZW50cxgBIAMoCSIfCgxQYXRoUmVzcG9uc2USDwoH",
            "cmVxX2FjaxgBIAEoCCI0CgxSZWFkUmVzcG9uc2USJAoLYmxvY2tSZWNvcmQY",
            "ASADKAsyDy5zdWZzLmJsb2NrUmVhZCI6CglibG9ja1JlYWQSDwoHQmxvY2tJ",
            "RBgBIAEoBRIOCgZETnJlYWQYAyADKAlKBAgCEANSBkROTGlzdCIYCghETmlk",
            "TGlzdBIMCgRETmlkGAEgASgJMtQDCghOYW1lTm9kZRI7CgpDcmVhdGVGaWxl",
            "EhMuc3Vmcy5DcmVhdGVSZXF1ZXN0GhQuc3Vmcy5DcmVhdGVSZXNwb25zZSIA",
            "MAESMAoJSGVhcnRiZWF0Eg8uc3Vmcy5IQnJlcXVlc3QaEC5zdWZzLkhCcmVz",
            "cG9uc2UiABI6CgtCbG9ja1JlcG9ydBITLnN1ZnMuUmVwb3J0UmVxdWVzdBoU",
            "LnN1ZnMuUmVwb3J0UmVzcG9uc2UiABI8Cg1MaXN0RGlyZWN0b3J5EhEuc3Vm",
            "cy5QYXRoUmVxdWVzdBoWLnN1ZnMuTGlzdFBhdGhSZXNwb25zZSIAEjcKDEFk",
            "ZERpcmVjdG9yeRIRLnN1ZnMuUGF0aFJlcXVlc3QaEi5zdWZzLlBhdGhSZXNw",
            "b25zZSIAEjoKD0RlbGV0ZURpcmVjdG9yeRIRLnN1ZnMuUGF0aFJlcXVlc3Qa",
            "Ei5zdWZzLlBhdGhSZXNwb25zZSIAEjUKCkRlbGV0ZUZpbGUSES5zdWZzLlBh",
            "dGhSZXF1ZXN0GhIuc3Vmcy5QYXRoUmVzcG9uc2UiABIzCghSZWFkRmlsZRIR",
            "LnN1ZnMuUGF0aFJlcXVlc3QaEi5zdWZzLlJlYWRSZXNwb25zZSIAYgZwcm90",
            "bzM="));

      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.CreateRequest), global::Sufs.CreateRequest.Parser, new[]{ "NumBlocks", "Dir", "FileName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.CreateResponse), global::Sufs.CreateResponse.Parser, new[]{ "BlockID", "RepFactor", "DNid" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.BlockID_Size), global::Sufs.BlockID_Size.Parser, new[]{ "BlockID", "BlockSize" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.ReportRequest), global::Sufs.ReportRequest.Parser, new[]{ "DNid", "BlockID" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.ReportResponse), global::Sufs.ReportResponse.Parser, new[]{ "Acknowledged" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.HBrequest), global::Sufs.HBrequest.Parser, new[]{ "DNid" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.HBresponse), global::Sufs.HBresponse.Parser, new[]{ "Acknowledged" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.PathRequest), global::Sufs.PathRequest.Parser, new[]{ "DirPath" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.ListPathResponse), global::Sufs.ListPathResponse.Parser, new[]{ "DirPathContents" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.PathResponse), global::Sufs.PathResponse.Parser, new[]{ "ReqAck" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.ReadResponse), global::Sufs.ReadResponse.Parser, new[]{ "BlockRecord" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.blockRead), global::Sufs.blockRead.Parser, new[]{ "BlockID", "DNread" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sufs.DNidList), global::Sufs.DNidList.Parser, new[]{ "DNid" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CreateRequest : pb::IMessage<CreateRequest> {
    private static readonly pb::MessageParser<CreateRequest> _parser = new pb::MessageParser<CreateRequest>(() => new CreateRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateRequest(CreateRequest other) : this() {
      numBlocks_ = other.numBlocks_;
      dir_ = other.dir_;
      fileName_ = other.fileName_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateRequest Clone() {
      return new CreateRequest(this);
    }

    /// <summary>Field number for the "numBlocks" field.</summary>
    public const int NumBlocksFieldNumber = 1;
    private int numBlocks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NumBlocks {
      get { return numBlocks_; }
      set {
        numBlocks_ = value;
      }
    }

    /// <summary>Field number for the "dir" field.</summary>
    public const int DirFieldNumber = 2;
    private string dir_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Dir {
      get { return dir_; }
      set {
        dir_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fileName" field.</summary>
    public const int FileNameFieldNumber = 3;
    private string fileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FileName {
      get { return fileName_; }
      set {
        fileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumBlocks != other.NumBlocks) return false;
      if (Dir != other.Dir) return false;
      if (FileName != other.FileName) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NumBlocks != 0) hash ^= NumBlocks.GetHashCode();
      if (Dir.Length != 0) hash ^= Dir.GetHashCode();
      if (FileName.Length != 0) hash ^= FileName.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NumBlocks != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(NumBlocks);
      }
      if (Dir.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Dir);
      }
      if (FileName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FileName);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NumBlocks != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumBlocks);
      }
      if (Dir.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Dir);
      }
      if (FileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileName);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateRequest other) {
      if (other == null) {
        return;
      }
      if (other.NumBlocks != 0) {
        NumBlocks = other.NumBlocks;
      }
      if (other.Dir.Length != 0) {
        Dir = other.Dir;
      }
      if (other.FileName.Length != 0) {
        FileName = other.FileName;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            NumBlocks = input.ReadInt32();
            break;
          }
          case 18: {
            Dir = input.ReadString();
            break;
          }
          case 26: {
            FileName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CreateResponse : pb::IMessage<CreateResponse> {
    private static readonly pb::MessageParser<CreateResponse> _parser = new pb::MessageParser<CreateResponse>(() => new CreateResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateResponse(CreateResponse other) : this() {
      blockID_ = other.blockID_;
      repFactor_ = other.repFactor_;
      dNid_ = other.dNid_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateResponse Clone() {
      return new CreateResponse(this);
    }

    /// <summary>Field number for the "blockID" field.</summary>
    public const int BlockIDFieldNumber = 2;
    private int blockID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BlockID {
      get { return blockID_; }
      set {
        blockID_ = value;
      }
    }

    /// <summary>Field number for the "repFactor" field.</summary>
    public const int RepFactorFieldNumber = 3;
    private int repFactor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RepFactor {
      get { return repFactor_; }
      set {
        repFactor_ = value;
      }
    }

    /// <summary>Field number for the "DNid" field.</summary>
    public const int DNidFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_dNid_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> dNid_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DNid {
      get { return dNid_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BlockID != other.BlockID) return false;
      if (RepFactor != other.RepFactor) return false;
      if(!dNid_.Equals(other.dNid_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BlockID != 0) hash ^= BlockID.GetHashCode();
      if (RepFactor != 0) hash ^= RepFactor.GetHashCode();
      hash ^= dNid_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BlockID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(BlockID);
      }
      if (RepFactor != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RepFactor);
      }
      dNid_.WriteTo(output, _repeated_dNid_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BlockID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BlockID);
      }
      if (RepFactor != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RepFactor);
      }
      size += dNid_.CalculateSize(_repeated_dNid_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateResponse other) {
      if (other == null) {
        return;
      }
      if (other.BlockID != 0) {
        BlockID = other.BlockID;
      }
      if (other.RepFactor != 0) {
        RepFactor = other.RepFactor;
      }
      dNid_.Add(other.dNid_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 16: {
            BlockID = input.ReadInt32();
            break;
          }
          case 24: {
            RepFactor = input.ReadInt32();
            break;
          }
          case 34: {
            dNid_.AddEntriesFrom(input, _repeated_dNid_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class BlockID_Size : pb::IMessage<BlockID_Size> {
    private static readonly pb::MessageParser<BlockID_Size> _parser = new pb::MessageParser<BlockID_Size>(() => new BlockID_Size());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BlockID_Size> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockID_Size() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockID_Size(BlockID_Size other) : this() {
      blockID_ = other.blockID_;
      blockSize_ = other.blockSize_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockID_Size Clone() {
      return new BlockID_Size(this);
    }

    /// <summary>Field number for the "blockID" field.</summary>
    public const int BlockIDFieldNumber = 1;
    private int blockID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BlockID {
      get { return blockID_; }
      set {
        blockID_ = value;
      }
    }

    /// <summary>Field number for the "blockSize" field.</summary>
    public const int BlockSizeFieldNumber = 2;
    private float blockSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float BlockSize {
      get { return blockSize_; }
      set {
        blockSize_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BlockID_Size);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BlockID_Size other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BlockID != other.BlockID) return false;
      if (BlockSize != other.BlockSize) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BlockID != 0) hash ^= BlockID.GetHashCode();
      if (BlockSize != 0F) hash ^= BlockSize.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BlockID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BlockID);
      }
      if (BlockSize != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(BlockSize);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BlockID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BlockID);
      }
      if (BlockSize != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BlockID_Size other) {
      if (other == null) {
        return;
      }
      if (other.BlockID != 0) {
        BlockID = other.BlockID;
      }
      if (other.BlockSize != 0F) {
        BlockSize = other.BlockSize;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            BlockID = input.ReadInt32();
            break;
          }
          case 21: {
            BlockSize = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReportRequest : pb::IMessage<ReportRequest> {
    private static readonly pb::MessageParser<ReportRequest> _parser = new pb::MessageParser<ReportRequest>(() => new ReportRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReportRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportRequest(ReportRequest other) : this() {
      dNid_ = other.dNid_;
      blockID_ = other.blockID_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportRequest Clone() {
      return new ReportRequest(this);
    }

    /// <summary>Field number for the "DNid" field.</summary>
    public const int DNidFieldNumber = 1;
    private string dNid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DNid {
      get { return dNid_; }
      set {
        dNid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "blockID" field.</summary>
    public const int BlockIDFieldNumber = 3;
    private int blockID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BlockID {
      get { return blockID_; }
      set {
        blockID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReportRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReportRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DNid != other.DNid) return false;
      if (BlockID != other.BlockID) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DNid.Length != 0) hash ^= DNid.GetHashCode();
      if (BlockID != 0) hash ^= BlockID.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DNid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DNid);
      }
      if (BlockID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BlockID);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DNid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DNid);
      }
      if (BlockID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BlockID);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReportRequest other) {
      if (other == null) {
        return;
      }
      if (other.DNid.Length != 0) {
        DNid = other.DNid;
      }
      if (other.BlockID != 0) {
        BlockID = other.BlockID;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            DNid = input.ReadString();
            break;
          }
          case 24: {
            BlockID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReportResponse : pb::IMessage<ReportResponse> {
    private static readonly pb::MessageParser<ReportResponse> _parser = new pb::MessageParser<ReportResponse>(() => new ReportResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReportResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportResponse(ReportResponse other) : this() {
      acknowledged_ = other.acknowledged_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportResponse Clone() {
      return new ReportResponse(this);
    }

    /// <summary>Field number for the "acknowledged" field.</summary>
    public const int AcknowledgedFieldNumber = 1;
    private bool acknowledged_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Acknowledged {
      get { return acknowledged_; }
      set {
        acknowledged_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReportResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReportResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Acknowledged != other.Acknowledged) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Acknowledged != false) hash ^= Acknowledged.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Acknowledged != false) {
        output.WriteRawTag(8);
        output.WriteBool(Acknowledged);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Acknowledged != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReportResponse other) {
      if (other == null) {
        return;
      }
      if (other.Acknowledged != false) {
        Acknowledged = other.Acknowledged;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Acknowledged = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class HBrequest : pb::IMessage<HBrequest> {
    private static readonly pb::MessageParser<HBrequest> _parser = new pb::MessageParser<HBrequest>(() => new HBrequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HBrequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HBrequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HBrequest(HBrequest other) : this() {
      dNid_ = other.dNid_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HBrequest Clone() {
      return new HBrequest(this);
    }

    /// <summary>Field number for the "DNid" field.</summary>
    public const int DNidFieldNumber = 1;
    private string dNid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DNid {
      get { return dNid_; }
      set {
        dNid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HBrequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HBrequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DNid != other.DNid) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DNid.Length != 0) hash ^= DNid.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DNid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DNid);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DNid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DNid);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HBrequest other) {
      if (other == null) {
        return;
      }
      if (other.DNid.Length != 0) {
        DNid = other.DNid;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            DNid = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class HBresponse : pb::IMessage<HBresponse> {
    private static readonly pb::MessageParser<HBresponse> _parser = new pb::MessageParser<HBresponse>(() => new HBresponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HBresponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HBresponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HBresponse(HBresponse other) : this() {
      acknowledged_ = other.acknowledged_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HBresponse Clone() {
      return new HBresponse(this);
    }

    /// <summary>Field number for the "acknowledged" field.</summary>
    public const int AcknowledgedFieldNumber = 1;
    private bool acknowledged_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Acknowledged {
      get { return acknowledged_; }
      set {
        acknowledged_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HBresponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HBresponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Acknowledged != other.Acknowledged) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Acknowledged != false) hash ^= Acknowledged.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Acknowledged != false) {
        output.WriteRawTag(8);
        output.WriteBool(Acknowledged);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Acknowledged != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HBresponse other) {
      if (other == null) {
        return;
      }
      if (other.Acknowledged != false) {
        Acknowledged = other.Acknowledged;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Acknowledged = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PathRequest : pb::IMessage<PathRequest> {
    private static readonly pb::MessageParser<PathRequest> _parser = new pb::MessageParser<PathRequest>(() => new PathRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PathRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PathRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PathRequest(PathRequest other) : this() {
      dirPath_ = other.dirPath_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PathRequest Clone() {
      return new PathRequest(this);
    }

    /// <summary>Field number for the "dir_path" field.</summary>
    public const int DirPathFieldNumber = 1;
    private string dirPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DirPath {
      get { return dirPath_; }
      set {
        dirPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PathRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PathRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DirPath != other.DirPath) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DirPath.Length != 0) hash ^= DirPath.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DirPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DirPath);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DirPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DirPath);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PathRequest other) {
      if (other == null) {
        return;
      }
      if (other.DirPath.Length != 0) {
        DirPath = other.DirPath;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            DirPath = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ListPathResponse : pb::IMessage<ListPathResponse> {
    private static readonly pb::MessageParser<ListPathResponse> _parser = new pb::MessageParser<ListPathResponse>(() => new ListPathResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ListPathResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListPathResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListPathResponse(ListPathResponse other) : this() {
      dirPathContents_ = other.dirPathContents_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListPathResponse Clone() {
      return new ListPathResponse(this);
    }

    /// <summary>Field number for the "dir_pathContents" field.</summary>
    public const int DirPathContentsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_dirPathContents_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> dirPathContents_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DirPathContents {
      get { return dirPathContents_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ListPathResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ListPathResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dirPathContents_.Equals(other.dirPathContents_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dirPathContents_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      dirPathContents_.WriteTo(output, _repeated_dirPathContents_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += dirPathContents_.CalculateSize(_repeated_dirPathContents_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ListPathResponse other) {
      if (other == null) {
        return;
      }
      dirPathContents_.Add(other.dirPathContents_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            dirPathContents_.AddEntriesFrom(input, _repeated_dirPathContents_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PathResponse : pb::IMessage<PathResponse> {
    private static readonly pb::MessageParser<PathResponse> _parser = new pb::MessageParser<PathResponse>(() => new PathResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PathResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PathResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PathResponse(PathResponse other) : this() {
      reqAck_ = other.reqAck_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PathResponse Clone() {
      return new PathResponse(this);
    }

    /// <summary>Field number for the "req_ack" field.</summary>
    public const int ReqAckFieldNumber = 1;
    private bool reqAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ReqAck {
      get { return reqAck_; }
      set {
        reqAck_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PathResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PathResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ReqAck != other.ReqAck) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ReqAck != false) hash ^= ReqAck.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ReqAck != false) {
        output.WriteRawTag(8);
        output.WriteBool(ReqAck);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ReqAck != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PathResponse other) {
      if (other == null) {
        return;
      }
      if (other.ReqAck != false) {
        ReqAck = other.ReqAck;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ReqAck = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReadResponse : pb::IMessage<ReadResponse> {
    private static readonly pb::MessageParser<ReadResponse> _parser = new pb::MessageParser<ReadResponse>(() => new ReadResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReadResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadResponse(ReadResponse other) : this() {
      blockRecord_ = other.blockRecord_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadResponse Clone() {
      return new ReadResponse(this);
    }

    /// <summary>Field number for the "blockRecord" field.</summary>
    public const int BlockRecordFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Sufs.blockRead> _repeated_blockRecord_codec
        = pb::FieldCodec.ForMessage(10, global::Sufs.blockRead.Parser);
    private readonly pbc::RepeatedField<global::Sufs.blockRead> blockRecord_ = new pbc::RepeatedField<global::Sufs.blockRead>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Sufs.blockRead> BlockRecord {
      get { return blockRecord_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReadResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReadResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!blockRecord_.Equals(other.blockRecord_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= blockRecord_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      blockRecord_.WriteTo(output, _repeated_blockRecord_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += blockRecord_.CalculateSize(_repeated_blockRecord_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReadResponse other) {
      if (other == null) {
        return;
      }
      blockRecord_.Add(other.blockRecord_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            blockRecord_.AddEntriesFrom(input, _repeated_blockRecord_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class blockRead : pb::IMessage<blockRead> {
    private static readonly pb::MessageParser<blockRead> _parser = new pb::MessageParser<blockRead>(() => new blockRead());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<blockRead> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public blockRead() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public blockRead(blockRead other) : this() {
      blockID_ = other.blockID_;
      dNread_ = other.dNread_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public blockRead Clone() {
      return new blockRead(this);
    }

    /// <summary>Field number for the "BlockID" field.</summary>
    public const int BlockIDFieldNumber = 1;
    private int blockID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BlockID {
      get { return blockID_; }
      set {
        blockID_ = value;
      }
    }

    /// <summary>Field number for the "DNread" field.</summary>
    public const int DNreadFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_dNread_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> dNread_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DNread {
      get { return dNread_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as blockRead);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(blockRead other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BlockID != other.BlockID) return false;
      if(!dNread_.Equals(other.dNread_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BlockID != 0) hash ^= BlockID.GetHashCode();
      hash ^= dNread_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BlockID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BlockID);
      }
      dNread_.WriteTo(output, _repeated_dNread_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BlockID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BlockID);
      }
      size += dNread_.CalculateSize(_repeated_dNread_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(blockRead other) {
      if (other == null) {
        return;
      }
      if (other.BlockID != 0) {
        BlockID = other.BlockID;
      }
      dNread_.Add(other.dNread_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            BlockID = input.ReadInt32();
            break;
          }
          case 26: {
            dNread_.AddEntriesFrom(input, _repeated_dNread_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class DNidList : pb::IMessage<DNidList> {
    private static readonly pb::MessageParser<DNidList> _parser = new pb::MessageParser<DNidList>(() => new DNidList());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DNidList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sufs.NameNodeReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DNidList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DNidList(DNidList other) : this() {
      dNid_ = other.dNid_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DNidList Clone() {
      return new DNidList(this);
    }

    /// <summary>Field number for the "DNid" field.</summary>
    public const int DNidFieldNumber = 1;
    private string dNid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DNid {
      get { return dNid_; }
      set {
        dNid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DNidList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DNidList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DNid != other.DNid) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DNid.Length != 0) hash ^= DNid.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DNid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DNid);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DNid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DNid);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DNidList other) {
      if (other == null) {
        return;
      }
      if (other.DNid.Length != 0) {
        DNid = other.DNid;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            DNid = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
