// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nameNode.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Sufs {
  public static partial class FileManagement
  {
    static readonly string __ServiceName = "sufs.FileManagement";

    static readonly grpc::Marshaller<global::Sufs.CreateRequest> __Marshaller_CreateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Sufs.CreateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Sufs.CreateResponse> __Marshaller_CreateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Sufs.CreateResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Sufs.CreateRequest, global::Sufs.CreateResponse> __Method_CreateFile = new grpc::Method<global::Sufs.CreateRequest, global::Sufs.CreateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateFile",
        __Marshaller_CreateRequest,
        __Marshaller_CreateResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Sufs.NameNodeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FileManagement</summary>
    public abstract partial class FileManagementBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Sufs.CreateResponse> CreateFile(global::Sufs.CreateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FileManagement</summary>
    public partial class FileManagementClient : grpc::ClientBase<FileManagementClient>
    {
      /// <summary>Creates a new client for FileManagement</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public FileManagementClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FileManagement that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public FileManagementClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected FileManagementClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected FileManagementClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Sufs.CreateResponse CreateFile(global::Sufs.CreateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateFile(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Sufs.CreateResponse CreateFile(global::Sufs.CreateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateFile, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Sufs.CreateResponse> CreateFileAsync(global::Sufs.CreateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateFileAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Sufs.CreateResponse> CreateFileAsync(global::Sufs.CreateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateFile, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override FileManagementClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FileManagementClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(FileManagementBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateFile, serviceImpl.CreateFile).Build();
    }

  }
  public static partial class BlockManagement
  {
    static readonly string __ServiceName = "sufs.BlockManagement";

    static readonly grpc::Marshaller<global::Sufs.ReportRequest> __Marshaller_ReportRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Sufs.ReportRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Sufs.ReportResponse> __Marshaller_ReportResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Sufs.ReportResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Sufs.ReportRequest, global::Sufs.ReportResponse> __Method_BlockReport = new grpc::Method<global::Sufs.ReportRequest, global::Sufs.ReportResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BlockReport",
        __Marshaller_ReportRequest,
        __Marshaller_ReportResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Sufs.NameNodeReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of BlockManagement</summary>
    public abstract partial class BlockManagementBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Sufs.ReportResponse> BlockReport(global::Sufs.ReportRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for BlockManagement</summary>
    public partial class BlockManagementClient : grpc::ClientBase<BlockManagementClient>
    {
      /// <summary>Creates a new client for BlockManagement</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BlockManagementClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BlockManagement that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BlockManagementClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BlockManagementClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BlockManagementClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Sufs.ReportResponse BlockReport(global::Sufs.ReportRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return BlockReport(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Sufs.ReportResponse BlockReport(global::Sufs.ReportRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BlockReport, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Sufs.ReportResponse> BlockReportAsync(global::Sufs.ReportRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return BlockReportAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Sufs.ReportResponse> BlockReportAsync(global::Sufs.ReportRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BlockReport, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BlockManagementClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BlockManagementClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BlockManagementBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_BlockReport, serviceImpl.BlockReport).Build();
    }

  }
  public static partial class Heartbeat
  {
    static readonly string __ServiceName = "sufs.Heartbeat";

    static readonly grpc::Marshaller<global::Sufs.HBrequest> __Marshaller_HBrequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Sufs.HBrequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Sufs.HBresponse> __Marshaller_HBresponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Sufs.HBresponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Sufs.HBrequest, global::Sufs.HBresponse> __Method_HeartbeatCheck = new grpc::Method<global::Sufs.HBrequest, global::Sufs.HBresponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HeartbeatCheck",
        __Marshaller_HBrequest,
        __Marshaller_HBresponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Sufs.NameNodeReflection.Descriptor.Services[2]; }
    }

    /// <summary>Base class for server-side implementations of Heartbeat</summary>
    public abstract partial class HeartbeatBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Sufs.HBresponse> HeartbeatCheck(global::Sufs.HBrequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Heartbeat</summary>
    public partial class HeartbeatClient : grpc::ClientBase<HeartbeatClient>
    {
      /// <summary>Creates a new client for Heartbeat</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HeartbeatClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Heartbeat that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HeartbeatClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HeartbeatClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HeartbeatClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Sufs.HBresponse HeartbeatCheck(global::Sufs.HBrequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return HeartbeatCheck(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Sufs.HBresponse HeartbeatCheck(global::Sufs.HBrequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HeartbeatCheck, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Sufs.HBresponse> HeartbeatCheckAsync(global::Sufs.HBrequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return HeartbeatCheckAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Sufs.HBresponse> HeartbeatCheckAsync(global::Sufs.HBrequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HeartbeatCheck, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HeartbeatClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HeartbeatClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HeartbeatBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_HeartbeatCheck, serviceImpl.HeartbeatCheck).Build();
    }

  }
}
#endregion
